# Generated by Django 2.2.5 on 2019-09-05 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Organizer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendee',
            name='drinks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Drink', to='event.Drink'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.ManyToManyField(to='event.Event'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Food', to='event.Food'),
        ),
    ]
