# Generated by Django 2.2.5 on 2019-09-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meat',
            field=models.CharField(choices=[('pork', 'PORK'), ('kitchen', 'KITCHEN'), ('beef', 'BEEF')], default=None, help_text='Meat for Bbq', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='public_invite_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Event details', null=True, verbose_name='Event Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(help_text='Final time', verbose_name='Event Final time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(help_text='Starting time', verbose_name='Event Starting time'),
        ),
    ]
