# Generated by Django 2.2.5 on 2019-09-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20190906_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='no_guests',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
