# Generated by Django 2.1.7 on 2019-09-05 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20190905_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees_names',
        ),
    ]
