# Generated by Django 2.1.7 on 2019-09-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_event_attendees_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='no_participants',
            field=models.IntegerField(blank=True, help_text='Number of Participants', null=True),
        ),
    ]
